---
title: "create-tag-array"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{create-tag-array}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mmmstan)
```

## Load Data
```{r load-data}
# Use observational data
load("~/github/sablefishData/data/sable_released.rda")
load("~/github/sablefishData/data/sable_recovered.rda")

```

## Create Tag Array (Yearly)
```{r create-tag-array-yearly}
# Arguments
x <- sable_released
y <- sable_recovered
time_step <- "year"
max_steps_liberty <- 3
release_date_colname <- "Release_Date"
release_area_colname <- "Release_Region"
group_colname <- "Release_Size"
recovery_date_colname <- "Recovery_Date"
recovery_area_colname <- "Recovery_Region"
id_colname <- "Tag_ID"
area_list <- list(ak = 1, bc = 2, wc = 3)
group_list <- list(small = 400:549, medium = 550:649, large = 650:799)
release_date_start <- c("1979-01-01")
release_date_end <- c("2016-12-31")

# Create Tag Array
tag_array <- create_tag_array(
  x,
  y,
  time_step,
  max_steps_liberty,
  release_date_colname,
  release_area_colname,
  group_colname,
  recovery_date_colname,
  recovery_area_colname,
  id_colname,
  area_list,
  group_list,
  release_date_start,
  release_date_end)

# Releases
sum(tag_array[,,,1,])

# Recoveries
sum(tag_array[,,,2:3,])

```

## Create Tag Array (Monthly)
```{r create-tag-array-monthly}
# Arguments
x <- sable_released
y <- sable_recovered
time_step <- "month"
max_steps_liberty <- 36
release_date_colname <- "Release_Date"
release_area_colname <- "Release_Region"
group_colname <- "Release_Size"
recovery_date_colname <- "Recovery_Date"
recovery_area_colname <- "Recovery_Region"
id_colname <- "Tag_ID"
area_list <- list(ak = 1, bc = 2, wc = 3)
group_list <- list(small = 400:549, medium = 550:649, large = 650:799)
release_date_start <- c("1979-01-01")
release_date_end <- c("2016-12-31")

# Create Tag Array
tag_array <- create_tag_array(
  x,
  y,
  time_step,
  max_steps_liberty,
  release_date_colname,
  release_area_colname,
  group_colname,
  recovery_date_colname,
  recovery_area_colname,
  id_colname,
  area_list,
  group_list,
  release_date_start,
  release_date_end)

# Releases
sum(tag_array[,,,1,])

# Recoveries
sum(tag_array[,,,2:36,])

```
