---
title: "fit-to-data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fit-to-data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mmmstan)
```

# Load data
```{r load-data}
if (FALSE) {
  # Define tag paths
  path_released <- "~/github/sablefish-data/data/tags_released.rda"
  path_recovered <- "~/github/sablefish-data/data/tags_recovered.rda"
  # Assign values
  tags_released <- read_from_path(path = path_released)
  tags_recovered <- read_from_path(path = path_recovered)
  # Tags
  tag_data <- tags_released %>%
    dplyr::left_join(
      tags_recovered,
      by = c(
        "tag_id", 
        "released_date", 
        "released_length", 
        "released_region", 
        "released_omregion", 
        "source"
      )
    )
  
  # Region arguments -----------------------------------------------------------
  
  # # Eight regions
  # list_regions <- list(ai = 1, bs = 2, wg = 3, cg = 4, eg = 5, se = 6, bc = 7, cc = 8)
  # movement_pattern <- 2
  # movement_allow <- matrix(c(5, 7, 7, 5), nrow = 2, byrow = TRUE)
  # movement_disallow <- NULL
  
  # Three regions
  list_regions <- list(ak = 1:6, bc = 7, cc = 8)
  movement_pattern <- 2
  movement_allow <- NULL
  movement_disallow <- NULL
  
  # Step arguments -------------------------------------------------------------
  
  step_interval <- "quarter"
  # step_duration_max <- NULL
  step_duration_max <- 12
  
  # Term arguments -------------------------------------------------------------
  
  term_interval <- "quarter"
  
  # Size arguments -------------------------------------------------------------
  
  # For fit mean
  list_sizes <- list(sml = 400:800)
  # For fit size
  list_sizes_small_large <- list(s = 400:549, l = 550:800)
 
  # Year arguments -------------------------------------------------------------
  
  year_start <- 1979
  year_end <- 2017
  
  # Model structure ------------------------------------------------------------
  
  model_time <- FALSE
  model_term <- FALSE
  model_size <- FALSE
  
  # Column name arguments ------------------------------------------------------
  
  colname_date_released <- "released_date" # "date_released"
  colname_date_recovered <- "recovered_date" # "date_recovered"
  colname_region_released <- "released_region" # "region_released"
  colname_region_recovered <- "recovered_region" # "region_recovered"
  colname_size_released <- "released_length" # "size_released"
  
  # Arguments with defaults ----------------------------------------------------
  
  # Movement step mean priors
  mu_movement_diag <- NULL
  sd_movement_diag <- NULL
  # Fishing rate priors
  mu_fishing_rate <- NULL
  cv_fishing_rate <- NULL
  # Selectivity priors
  mu_selectivity <- NULL
  sd_selectivity <- NULL
  # Fishing weight priors
  mu_fishing_weight <- NULL
  sd_fishing_weight <- NULL
  # Natural mortality rate priors
  mu_natural_mortality_rate <- NULL
  sd_natural_mortality_rate <- NULL
  # Fractional (per tag) reporting rate priors
  mu_reporting_rate <- NULL
  sd_reporting_rate <- NULL
  # Fractional (per tag) initial loss rate priors
  mu_initial_loss_rate <- 0.1
  sd_initial_loss_rate <- 0.01
  # Instantaneous ongoing loss rate priors
  mu_ongoing_loss_rate <- 0.02
  sd_ongoing_loss_rate <- 0.001
  # AR1 time coefficient priors
  mu_phi_time <- 0.25
  sd_phi_time <- 0.05
  # AR1 term coefficient priors
  mu_phi_term <- 0.25
  sd_phi_term <- 0.05
  # AR1 time sigma priors
  mu_sigma_time <- 0.005
  sd_sigma_time <- 0.001
  # AR1 term sigma priors
  mu_sigma_term <- 0.005
  sd_sigma_term <- 0.001
  # RE size sigma priors
  mu_sigma_size <- 0.005
  sd_sigma_size <- 0.001  
  # Dispersion priors
  mu_dispersion <- 1.0
  sd_dispersion <- 0.5
  # Tolerance values
  tolerance_expected <- 1e-12
  tolerance_fishing <-  1e-12
  # CmdStanR
  data <- NULL
  chains <- 1
  step_size <- 0.01
  adapt_delta <- 0.95
  iter_warmup <- 250
  iter_sampling <- 750
  max_treedepth <- 10
  threads_per_chain <- parallel::detectCores()/(2*chains)

  # Use reduce sum -------------------------------------------------------------
  
  use_reduce_sum <- FALSE
  # use_reduce_sum <- TRUE
  refresh <- 10
}

```

# Fit mean
```{r fit-mean}
if (FALSE) {
  # Fit mean
  fit_mean <- mmmstan(
    tag_data = tag_data,
    # Tag arguments
    list_regions = list_regions,
    list_sizes = list_sizes,
    year_start = year_start,
    year_end = year_end,
    step_interval = step_interval,
    step_duration_max = step_duration_max,
    term_interval = term_interval,
    colname_date_released = colname_date_released, # "date_released",
    colname_date_recovered = colname_date_recovered, # "date_recovered",
    colname_region_released = colname_region_released, # "region_released",
    colname_region_recovered = colname_region_recovered, # "region_recovered",
    colname_size_released = colname_size_released, # "size_released",
    # Model structure
    model_time = FALSE,
    model_term = FALSE,
    model_size = FALSE,
    # Movement index
    movement_pattern = movement_pattern,
    movement_allow = movement_allow,
    movement_disallow = movement_disallow,
    # Use reduce sum
    use_reduce_sum = use_reduce_sum,
    refresh = refresh
  )
  # View
  tibble::view(fit_mean$summary$movement_mean)
  tibble::view(fit_mean$summary$fishing_rate)
  # Plot
  ggplot2::ggplot(
    data = fit_mean$summary$movement_mean,
    mapping = ggplot2::aes(
      x = 1,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$x),
      cols = ggplot2::vars(.data$y)
    ) +
    ggsidekick::theme_sleek()
}

```

# Fit time
```{r fit-time}
if (FALSE) {
  # Fit time
  fit_time <- mmmstan(
    tag_data = tag_data,
    # Tag arguments
    list_regions = list_regions,
    list_sizes = list_sizes,
    year_start = year_start,
    year_end = year_end,
    step_interval = step_interval,
    step_duration_max = step_duration_max,
    term_interval = term_interval,
    colname_date_released = colname_date_released, # "date_released",
    colname_date_recovered = colname_date_recovered, # "date_recovered",
    colname_region_released = colname_region_released, # "region_released",
    colname_region_recovered = colname_region_recovered, # "region_recovered",
    colname_size_released = colname_size_released, # "size_released",
    # Model structure
    model_time = TRUE,
    model_term = FALSE,
    model_size = FALSE,
    # Movement index
    movement_pattern = movement_pattern,
    movement_allow = movement_allow,
    movement_disallow = movement_disallow,
    # AR1 time sigma priors
    mu_sigma_time = mu_sigma_time,
    sd_sigma_time = sd_sigma_time,
    # AR1 term sigma priors
    mu_sigma_term = mu_sigma_term,
    sd_sigma_term = sd_sigma_term,
    # Use reduce sum
    use_reduce_sum = use_reduce_sum,
    refresh = refresh
  )
  # View
  tibble::view(fit_time$summary$movement_mean)
  tibble::view(fit_time$summary$movement_time)
  tibble::view(fit_time$summary$fishing_rate)
  tibble::view(fit_time$summary$phi_time)
  tibble::view(fit_time$summary$sigma_time)
  # Function
  region_abbrev <- function(x) c("AK", "BC", "CC")[x]
  # Wrangle
  movement_time <- fit_time$summary$movement_time %>%
    dplyr::mutate(
      region_start = region_abbrev(.data$x),
      region_end = region_abbrev(.data$y),
      year = .data$t + 1978
    )
  tibble::view(movement_time)
  # Plot
  ggplot2::ggplot(
    data = fit_time$summary$movement_mean,
    mapping = ggplot2::aes(
      x = 1,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$x),
      cols = ggplot2::vars(.data$y)
    ) +
    ggsidekick::theme_sleek()
  # Plot time
  ggplot2::ggplot(
    data = movement_time, # fit_time$summary$movement_time
    mapping = ggplot2::aes(
      x = .data$year,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$region_start),
      cols = ggplot2::vars(.data$region_end)
    ) +
    ggplot2::xlab("Year") + 
    ggplot2::ylab("Annual movement rate") +
    ggsidekick::theme_sleek()
  # Save
  ggplot2::ggsave(
    "sablefish-timevarying.pdf", width = 190, height = 140, units = "mm"
  )
}

```

# Fit term
```{r fit-term}
if (FALSE) {
  # Fit term
  fit_term <- mmmstan(
    tag_data = tag_data,
    # Tag arguments
    list_regions = list_regions,
    list_sizes = list_sizes,
    year_start = year_start,
    year_end = year_end,
    step_interval = step_interval,
    step_duration_max = step_duration_max,
    term_interval = term_interval,
    colname_date_released = colname_date_released, # "date_released",
    colname_date_recovered = colname_date_recovered, # "date_recovered",
    colname_region_released = colname_region_released, # "region_released",
    colname_region_recovered = colname_region_recovered, # "region_recovered",
    colname_size_released = colname_size_released, # "size_released",
    # Model structure
    model_time = FALSE,
    model_term = TRUE,
    model_size = FALSE,
    # Movement index
    movement_pattern = movement_pattern,
    movement_allow = movement_allow,
    movement_disallow = movement_disallow,
    # AR1 time sigma priors
    mu_sigma_time = mu_sigma_time,
    sd_sigma_time = sd_sigma_time,
    # AR1 term sigma priors
    mu_sigma_term = mu_sigma_term,
    sd_sigma_term = sd_sigma_term,
    # Use reduce sum
    use_reduce_sum = use_reduce_sum,
    refresh = refresh
  )
  # View
  tibble::view(fit_term$summary$movement_mean)
  tibble::view(fit_term$summary$movement_term)
  tibble::view(fit_term$summary$fishing_rate)
  # Plot mean
  ggplot2::ggplot(
    data = fit_term$summary$movement_mean,
    mapping = ggplot2::aes(
      x = 1,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$x),
      cols = ggplot2::vars(.data$y)
    ) +
    ggsidekick::theme_sleek()
  # Plot term
  ggplot2::ggplot(
    data = fit_term$summary$movement_term,
    mapping = ggplot2::aes(
      x = .data$k,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$x),
      cols = ggplot2::vars(.data$y)
    ) +
    ggsidekick::theme_sleek()
}

```

# Fit size
```{r fit-size}
if (FALSE) {
  # Fit size
  fit_size <- mmmstan(
    tag_data = tag_data,
    # Tag arguments
    list_regions = list_regions,
    list_sizes = list_sizes_small_large,
    year_start = year_start,
    year_end = year_end,
    step_interval = step_interval,
    step_duration_max = step_duration_max,
    term_interval = term_interval,
    colname_date_released = colname_date_released, # "date_released",
    colname_date_recovered = colname_date_recovered, # "date_recovered",
    colname_region_released = colname_region_released, # "region_released",
    colname_region_recovered = colname_region_recovered, # "region_recovered",
    colname_size_released = colname_size_released, # "size_released",
    # Model structure
    model_time = FALSE,
    model_term = FALSE,
    model_size = TRUE,
    # Movement index
    movement_pattern = movement_pattern,
    movement_allow = movement_allow,
    movement_disallow = movement_disallow,
    # RE size sigma priors
    mu_sigma_size = mu_sigma_size,
    sd_sigma_size = sd_sigma_size, 
    # Use reduce sum
    use_reduce_sum = use_reduce_sum,
    refresh = refresh
  )
  # View
  tibble::view(fit_size$summary$movement_mean)
  tibble::view(fit_size$summary$movement_size)
  tibble::view(fit_size$summary$fishing_rate)
  # Plot mean
  ggplot2::ggplot(
    data = fit_size$summary$movement_mean,
    mapping = ggplot2::aes(
      x = 1,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$x),
      cols = ggplot2::vars(.data$y)
    ) +
    ggsidekick::theme_sleek()
  # Plot size
  ggplot2::ggplot(
    data = fit_size$summary$movement_size,
    mapping = ggplot2::aes(
      x = .data$l,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$x),
      cols = ggplot2::vars(.data$y)
    ) +
    ggsidekick::theme_sleek()
}

```

# Fit time and term
```{r fit-time-term}
if (FALSE) {
  # Fit time and term
  fit_time_term <- mmmstan(
    tag_data = tag_data,
    # Tag arguments
    list_regions = list_regions,
    list_sizes = list_sizes,
    year_start = year_start,
    year_end = year_end,
    step_interval = step_interval,
    step_duration_max = step_duration_max,
    term_interval = term_interval,
    colname_date_released = colname_date_released, # "date_released",
    colname_date_recovered = colname_date_recovered, # "date_recovered",
    colname_region_released = colname_region_released, # "region_released",
    colname_region_recovered = colname_region_recovered, # "region_recovered",
    colname_size_released = colname_size_released, # "size_released",
    # Model structure
    model_time = TRUE,
    model_term = TRUE,
    model_size = FALSE,
    # Movement index
    movement_pattern = movement_pattern,
    movement_allow = movement_allow,
    movement_disallow = movement_disallow,
    # AR1 time sigma priors
    mu_sigma_time = mu_sigma_time / 10,
    sd_sigma_time = sd_sigma_time / 10,
    # AR1 term sigma priors
    mu_sigma_term = mu_sigma_term / 10,
    sd_sigma_term = sd_sigma_term / 10,
    # Use reduce sum
    use_reduce_sum = use_reduce_sum,
    refresh = refresh
  )
  # View
  tibble::view(fit_time_term$summary$movement_mean)
  tibble::view(fit_time_term$summary$movement_time)
  tibble::view(fit_time_term$summary$movement_term)
  tibble::view(fit_time_term$summary$fishing_rate)
  tibble::view(fit_time_term$summary$phi_time)
  tibble::view(fit_time_term$summary$sigma_time)
  # Plot
  ggplot2::ggplot(
    data = fit_time_term$summary$movement_mean,
    mapping = ggplot2::aes(
      x = 1,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$x),
      cols = ggplot2::vars(.data$y)
    ) +
    ggsidekick::theme_sleek()
  # Plot time
  ggplot2::ggplot(
    data = fit_time_term$summary$movement_time,
    mapping = ggplot2::aes(
      x = .data$t,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$x),
      cols = ggplot2::vars(.data$y)
    ) +
    ggsidekick::theme_sleek()
  # Plot term
  ggplot2::ggplot(
    data = fit_time_term$summary$movement_term,
    mapping = ggplot2::aes(
      x = .data$k,
      y = .data$mean
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data$x),
      cols = ggplot2::vars(.data$y)
    ) +
    ggsidekick::theme_sleek()
}

```
