// Generated by rstantools.  Do not edit by hand.

/*
    mmmstan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    mmmstan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with mmmstan.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_mmm_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_mmm");
    reader.add_event(214, 212, "end", "model_mmm");
    return reader;
}
template <typename T0__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__>::type, Eigen::Dynamic, Eigen::Dynamic>
mat_power(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& a,
              const int& n, std::ostream* pstream__);
template <typename T0__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__>::type, Eigen::Dynamic, Eigen::Dynamic>
mat_power(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& a,
              const int& n, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 6;
        if (as_bool(logical_eq(n, 0))) {
            current_statement_begin__ = 7;
            return stan::math::promote_scalar<fun_return_scalar_t__>(diag_matrix(rep_vector(1, rows(a))));
        } else if (as_bool(logical_eq(n, 1))) {
            current_statement_begin__ = 9;
            return stan::math::promote_scalar<fun_return_scalar_t__>(a);
        } else {
            current_statement_begin__ = 11;
            return stan::math::promote_scalar<fun_return_scalar_t__>(multiply(a, mat_power(a, (n - 1), pstream__)));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct mat_power_functor__ {
    template <typename T0__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__>::type, Eigen::Dynamic, Eigen::Dynamic>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& a,
              const int& n, std::ostream* pstream__) const {
        return mat_power(a, n, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_mmm
  : public stan::model::model_base_crtp<model_mmm> {
private:
        int A;
        int G;
        int L;
        int T;
        int Y;
        std::vector<std::vector<std::vector<std::vector<std::vector<int> > > > > x;
        double u;
        double v;
        double m;
        std::vector<double> h_alpha;
        std::vector<double> h_beta;
        int ST;
        int YT;
public:
    model_mmm(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_mmm(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_mmm_namespace::model_mmm";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 17;
            context__.validate_dims("data initialization", "A", "int", context__.to_vec());
            A = int(0);
            vals_i__ = context__.vals_i("A");
            pos__ = 0;
            A = vals_i__[pos__++];
            check_greater_or_equal(function__, "A", A, 2);
            current_statement_begin__ = 18;
            context__.validate_dims("data initialization", "G", "int", context__.to_vec());
            G = int(0);
            vals_i__ = context__.vals_i("G");
            pos__ = 0;
            G = vals_i__[pos__++];
            check_greater_or_equal(function__, "G", G, 1);
            current_statement_begin__ = 19;
            context__.validate_dims("data initialization", "L", "int", context__.to_vec());
            L = int(0);
            vals_i__ = context__.vals_i("L");
            pos__ = 0;
            L = vals_i__[pos__++];
            check_greater_or_equal(function__, "L", L, 2);
            current_statement_begin__ = 20;
            context__.validate_dims("data initialization", "T", "int", context__.to_vec());
            T = int(0);
            vals_i__ = context__.vals_i("T");
            pos__ = 0;
            T = vals_i__[pos__++];
            check_greater_or_equal(function__, "T", T, 1);
            current_statement_begin__ = 22;
            context__.validate_dims("data initialization", "Y", "int", context__.to_vec());
            Y = int(0);
            vals_i__ = context__.vals_i("Y");
            pos__ = 0;
            Y = vals_i__[pos__++];
            check_greater_or_equal(function__, "Y", Y, 1);
            current_statement_begin__ = 24;
            validate_non_negative_index("x", "T", T);
            validate_non_negative_index("x", "A", A);
            validate_non_negative_index("x", "G", G);
            validate_non_negative_index("x", "L", L);
            validate_non_negative_index("x", "A", A);
            context__.validate_dims("data initialization", "x", "int", context__.to_vec(T,A,G,L,A));
            x = std::vector<std::vector<std::vector<std::vector<std::vector<int> > > > >(T, std::vector<std::vector<std::vector<std::vector<int> > > >(A, std::vector<std::vector<std::vector<int> > >(G, std::vector<std::vector<int> >(L, std::vector<int>(A, int(0))))));
            vals_i__ = context__.vals_i("x");
            pos__ = 0;
            size_t x_k_0_max__ = T;
            size_t x_k_1_max__ = A;
            size_t x_k_2_max__ = G;
            size_t x_k_3_max__ = L;
            size_t x_k_4_max__ = A;
            for (size_t k_4__ = 0; k_4__ < x_k_4_max__; ++k_4__) {
                for (size_t k_3__ = 0; k_3__ < x_k_3_max__; ++k_3__) {
                    for (size_t k_2__ = 0; k_2__ < x_k_2_max__; ++k_2__) {
                        for (size_t k_1__ = 0; k_1__ < x_k_1_max__; ++k_1__) {
                            for (size_t k_0__ = 0; k_0__ < x_k_0_max__; ++k_0__) {
                                x[k_0__][k_1__][k_2__][k_3__][k_4__] = vals_i__[pos__++];
                            }
                        }
                    }
                }
            }
            size_t x_i_0_max__ = T;
            size_t x_i_1_max__ = A;
            size_t x_i_2_max__ = G;
            size_t x_i_3_max__ = L;
            size_t x_i_4_max__ = A;
            for (size_t i_0__ = 0; i_0__ < x_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < x_i_1_max__; ++i_1__) {
                    for (size_t i_2__ = 0; i_2__ < x_i_2_max__; ++i_2__) {
                        for (size_t i_3__ = 0; i_3__ < x_i_3_max__; ++i_3__) {
                            for (size_t i_4__ = 0; i_4__ < x_i_4_max__; ++i_4__) {
                                check_greater_or_equal(function__, "x[i_0__][i_1__][i_2__][i_3__][i_4__]", x[i_0__][i_1__][i_2__][i_3__][i_4__], 0);
                            }
                        }
                    }
                }
            }
            current_statement_begin__ = 26;
            context__.validate_dims("data initialization", "u", "double", context__.to_vec());
            u = double(0);
            vals_r__ = context__.vals_r("u");
            pos__ = 0;
            u = vals_r__[pos__++];
            check_greater_or_equal(function__, "u", u, 0);
            check_less_or_equal(function__, "u", u, 1);
            current_statement_begin__ = 27;
            context__.validate_dims("data initialization", "v", "double", context__.to_vec());
            v = double(0);
            vals_r__ = context__.vals_r("v");
            pos__ = 0;
            v = vals_r__[pos__++];
            check_greater_or_equal(function__, "v", v, 0);
            current_statement_begin__ = 28;
            context__.validate_dims("data initialization", "m", "double", context__.to_vec());
            m = double(0);
            vals_r__ = context__.vals_r("m");
            pos__ = 0;
            m = vals_r__[pos__++];
            check_greater_or_equal(function__, "m", m, 0);
            current_statement_begin__ = 30;
            validate_non_negative_index("h_alpha", "A", A);
            context__.validate_dims("data initialization", "h_alpha", "double", context__.to_vec(A));
            h_alpha = std::vector<double>(A, double(0));
            vals_r__ = context__.vals_r("h_alpha");
            pos__ = 0;
            size_t h_alpha_k_0_max__ = A;
            for (size_t k_0__ = 0; k_0__ < h_alpha_k_0_max__; ++k_0__) {
                h_alpha[k_0__] = vals_r__[pos__++];
            }
            size_t h_alpha_i_0_max__ = A;
            for (size_t i_0__ = 0; i_0__ < h_alpha_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "h_alpha[i_0__]", h_alpha[i_0__], 0);
            }
            current_statement_begin__ = 31;
            validate_non_negative_index("h_beta", "A", A);
            context__.validate_dims("data initialization", "h_beta", "double", context__.to_vec(A));
            h_beta = std::vector<double>(A, double(0));
            vals_r__ = context__.vals_r("h_beta");
            pos__ = 0;
            size_t h_beta_k_0_max__ = A;
            for (size_t k_0__ = 0; k_0__ < h_beta_k_0_max__; ++k_0__) {
                h_beta[k_0__] = vals_r__[pos__++];
            }
            size_t h_beta_i_0_max__ = A;
            for (size_t i_0__ = 0; i_0__ < h_beta_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "h_beta[i_0__]", h_beta[i_0__], 0);
            }
            // initialize transformed data variables
            current_statement_begin__ = 36;
            ST = int(0);
            stan::math::fill(ST, std::numeric_limits<int>::min());
            stan::math::assign(ST,(T + (L - 1)));
            current_statement_begin__ = 37;
            YT = int(0);
            stan::math::fill(YT, std::numeric_limits<int>::min());
            stan::math::assign(YT,0);
            // execute transformed data statements
            current_statement_begin__ = 38;
            for (int mt = 1; mt <= T; ++mt) {
                current_statement_begin__ = 39;
                for (int ma = 1; ma <= A; ++ma) {
                    current_statement_begin__ = 40;
                    for (int mg = 1; mg <= G; ++mg) {
                        current_statement_begin__ = 41;
                        if (as_bool(logical_gt(get_base1(get_base1(get_base1(get_base1(get_base1(x, mt, "x", 1), ma, "x", 2), mg, "x", 3), 1, "x", 4), ma, "x", 5), 0))) {
                            current_statement_begin__ = 42;
                            stan::math::assign(YT, (YT + (L * A)));
                        }
                    }
                }
            }
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 51;
            validate_non_negative_index("h", "A", A);
            num_params_r__ += (1 * A);
            current_statement_begin__ = 53;
            validate_non_negative_index("p11", "2", 2);
            num_params_r__ += (2 - 1);
            current_statement_begin__ = 54;
            validate_non_negative_index("p12", "3", 3);
            num_params_r__ += (3 - 1);
            current_statement_begin__ = 55;
            validate_non_negative_index("p13", "2", 2);
            num_params_r__ += (2 - 1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_mmm() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 51;
        if (!(context__.contains_r("h")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable h missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("h");
        pos__ = 0U;
        validate_non_negative_index("h", "A", A);
        context__.validate_dims("parameter initialization", "h", "double", context__.to_vec(A));
        std::vector<double> h(A, double(0));
        size_t h_k_0_max__ = A;
        for (size_t k_0__ = 0; k_0__ < h_k_0_max__; ++k_0__) {
            h[k_0__] = vals_r__[pos__++];
        }
        size_t h_i_0_max__ = A;
        for (size_t i_0__ = 0; i_0__ < h_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lub_unconstrain(0, 1, h[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable h: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 53;
        if (!(context__.contains_r("p11")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable p11 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("p11");
        pos__ = 0U;
        validate_non_negative_index("p11", "2", 2);
        context__.validate_dims("parameter initialization", "p11", "vector_d", context__.to_vec(2));
        Eigen::Matrix<double, Eigen::Dynamic, 1> p11(2);
        size_t p11_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < p11_j_1_max__; ++j_1__) {
            p11(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.simplex_unconstrain(p11);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable p11: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 54;
        if (!(context__.contains_r("p12")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable p12 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("p12");
        pos__ = 0U;
        validate_non_negative_index("p12", "3", 3);
        context__.validate_dims("parameter initialization", "p12", "vector_d", context__.to_vec(3));
        Eigen::Matrix<double, Eigen::Dynamic, 1> p12(3);
        size_t p12_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < p12_j_1_max__; ++j_1__) {
            p12(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.simplex_unconstrain(p12);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable p12: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 55;
        if (!(context__.contains_r("p13")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable p13 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("p13");
        pos__ = 0U;
        validate_non_negative_index("p13", "2", 2);
        context__.validate_dims("parameter initialization", "p13", "vector_d", context__.to_vec(2));
        Eigen::Matrix<double, Eigen::Dynamic, 1> p13(2);
        size_t p13_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < p13_j_1_max__; ++j_1__) {
            p13(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.simplex_unconstrain(p13);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable p13: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 51;
            std::vector<local_scalar_t__> h;
            size_t h_d_0_max__ = A;
            h.reserve(h_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < h_d_0_max__; ++d_0__) {
                if (jacobian__)
                    h.push_back(in__.scalar_lub_constrain(0, 1, lp__));
                else
                    h.push_back(in__.scalar_lub_constrain(0, 1));
            }
            current_statement_begin__ = 53;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> p11;
            (void) p11;  // dummy to suppress unused var warning
            if (jacobian__)
                p11 = in__.simplex_constrain(2, lp__);
            else
                p11 = in__.simplex_constrain(2);
            current_statement_begin__ = 54;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> p12;
            (void) p12;  // dummy to suppress unused var warning
            if (jacobian__)
                p12 = in__.simplex_constrain(3, lp__);
            else
                p12 = in__.simplex_constrain(3);
            current_statement_begin__ = 55;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> p13;
            (void) p13;  // dummy to suppress unused var warning
            if (jacobian__)
                p13 = in__.simplex_constrain(2, lp__);
            else
                p13 = in__.simplex_constrain(2);
            // transformed parameters
            current_statement_begin__ = 67;
            validate_non_negative_index("f", "A", A);
            std::vector<local_scalar_t__> f(A, local_scalar_t__(0));
            stan::math::initialize(f, DUMMY_VAR__);
            stan::math::fill(f, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 68;
            for (int ca = 1; ca <= A; ++ca) {
                current_statement_begin__ = 69;
                stan::model::assign(f, 
                            stan::model::cons_list(stan::model::index_uni(ca), stan::model::nil_index_list()), 
                            -(stan::math::log((1 - get_base1(h, ca, "h", 1)))), 
                            "assigning variable f");
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 67;
            size_t f_k_0_max__ = A;
            for (size_t k_0__ = 0; k_0__ < f_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(f[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: f" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable f: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            {
            current_statement_begin__ = 103;
            validate_non_negative_index("p", "G", G);
            validate_non_negative_index("p", "A", A);
            validate_non_negative_index("p", "A", A);
            std::vector<std::vector<std::vector<local_scalar_t__  >  >  > p(G, std::vector<std::vector<local_scalar_t__> >(A, std::vector<local_scalar_t__>(A, local_scalar_t__(DUMMY_VAR__))));
            stan::math::initialize(p, DUMMY_VAR__);
            stan::math::fill(p, DUMMY_VAR__);
            current_statement_begin__ = 105;
            validate_non_negative_index("n", "T", T);
            validate_non_negative_index("n", "A", A);
            validate_non_negative_index("n", "G", G);
            validate_non_negative_index("n", "L", L);
            validate_non_negative_index("n", "A", A);
            std::vector<std::vector<std::vector<std::vector<std::vector<local_scalar_t__  >  >  >  >  > n(T, std::vector<std::vector<std::vector<std::vector<local_scalar_t__> > > >(A, std::vector<std::vector<std::vector<local_scalar_t__> > >(G, std::vector<std::vector<local_scalar_t__> >(L, std::vector<local_scalar_t__>(A, local_scalar_t__(DUMMY_VAR__))))));
            stan::math::initialize(n, DUMMY_VAR__);
            stan::math::fill(n, DUMMY_VAR__);
            current_statement_begin__ = 106;
            validate_non_negative_index("s", "G", G);
            validate_non_negative_index("s", "ST", ST);
            validate_non_negative_index("s", "A", A);
            std::vector<std::vector<std::vector<local_scalar_t__  >  >  > s(G, std::vector<std::vector<local_scalar_t__> >(ST, std::vector<local_scalar_t__>(A, local_scalar_t__(DUMMY_VAR__))));
            stan::math::initialize(s, DUMMY_VAR__);
            stan::math::fill(s, DUMMY_VAR__);
            current_statement_begin__ = 107;
            validate_non_negative_index("y_vec", "YT", YT);
            std::vector<int  > y_vec(YT, int(0));
            stan::math::fill(y_vec, std::numeric_limits<int>::min());
            current_statement_begin__ = 108;
            validate_non_negative_index("y_hat", "YT", YT);
            std::vector<local_scalar_t__  > y_hat(YT, local_scalar_t__(DUMMY_VAR__));
            stan::math::initialize(y_hat, DUMMY_VAR__);
            stan::math::fill(y_hat, DUMMY_VAR__);
            current_statement_begin__ = 109;
            int y_ind(0);
            (void) y_ind;  // dummy to suppress unused var warning
            stan::math::fill(y_ind, std::numeric_limits<int>::min());
            current_statement_begin__ = 110;
            validate_non_negative_index("n_sub", "T", T);
            validate_non_negative_index("n_sub", "A", A);
            std::vector<std::vector<local_scalar_t__  >  > n_sub(T, std::vector<local_scalar_t__>(A, local_scalar_t__(DUMMY_VAR__)));
            stan::math::initialize(n_sub, DUMMY_VAR__);
            stan::math::fill(n_sub, DUMMY_VAR__);
            current_statement_begin__ = 111;
            stan::math::assign(n, rep_array(rep_array(0, L, A), T, A, G));
            current_statement_begin__ = 112;
            stan::math::assign(s, rep_array(0, G, ST, A));
            current_statement_begin__ = 113;
            stan::math::assign(y_vec, rep_array(0, YT));
            current_statement_begin__ = 114;
            stan::math::assign(y_hat, rep_array(0, YT));
            current_statement_begin__ = 115;
            stan::math::assign(y_ind, 1);
            current_statement_begin__ = 118;
            stan::math::assign(p, rep_array(1e-12, G, A, A));
            current_statement_begin__ = 120;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()))), 
                        get_base1(p11, 1, "p11", 1), 
                        "assigning variable p");
            current_statement_begin__ = 121;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()))), 
                        get_base1(p11, 2, "p11", 1), 
                        "assigning variable p");
            current_statement_begin__ = 122;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()))), 
                        get_base1(p12, 1, "p12", 1), 
                        "assigning variable p");
            current_statement_begin__ = 123;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()))), 
                        get_base1(p12, 2, "p12", 1), 
                        "assigning variable p");
            current_statement_begin__ = 124;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(3), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()))), 
                        get_base1(p12, 3, "p12", 1), 
                        "assigning variable p");
            current_statement_begin__ = 125;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()))), 
                        get_base1(p13, 1, "p13", 1), 
                        "assigning variable p");
            current_statement_begin__ = 126;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(3), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()))), 
                        get_base1(p13, 2, "p13", 1), 
                        "assigning variable p");
            current_statement_begin__ = 129;
            for (int mg = 1; mg <= G; ++mg) {
                current_statement_begin__ = 130;
                for (int ct = 1; ct <= ST; ++ct) {
                    current_statement_begin__ = 131;
                    for (int ca = 1; ca <= A; ++ca) {
                        current_statement_begin__ = 132;
                        stan::model::assign(s, 
                                    stan::model::cons_list(stan::model::index_uni(mg), stan::model::cons_list(stan::model::index_uni(ct), stan::model::cons_list(stan::model::index_uni(ca), stan::model::nil_index_list()))), 
                                    stan::math::exp(((-(get_base1(f, ca, "f", 1)) - m) - v)), 
                                    "assigning variable s");
                    }
                }
            }
            current_statement_begin__ = 138;
            for (int mt = 1; mt <= T; ++mt) {
                current_statement_begin__ = 139;
                for (int ma = 1; ma <= A; ++ma) {
                    current_statement_begin__ = 140;
                    for (int mg = 1; mg <= G; ++mg) {
                        current_statement_begin__ = 141;
                        stan::model::assign(n, 
                                    stan::model::cons_list(stan::model::index_uni(mt), stan::model::cons_list(stan::model::index_uni(ma), stan::model::cons_list(stan::model::index_uni(mg), stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(ma), stan::model::nil_index_list()))))), 
                                    (u * get_base1(get_base1(get_base1(get_base1(get_base1(x, mt, "x", 1), ma, "x", 2), mg, "x", 3), 1, "x", 4), ma, "x", 5)), 
                                    "assigning variable n");
                    }
                }
            }
            current_statement_begin__ = 147;
            for (int mt = 1; mt <= T; ++mt) {
                current_statement_begin__ = 148;
                for (int ma = 1; ma <= A; ++ma) {
                    current_statement_begin__ = 149;
                    for (int mg = 1; mg <= G; ++mg) {
                        current_statement_begin__ = 150;
                        if (as_bool(logical_gt(get_base1(get_base1(get_base1(get_base1(get_base1(x, mt, "x", 1), ma, "x", 2), mg, "x", 3), 1, "x", 4), ma, "x", 5), 0))) {
                            current_statement_begin__ = 151;
                            for (int cl = 2; cl <= L; ++cl) {
                                current_statement_begin__ = 152;
                                for (int ca = 1; ca <= A; ++ca) {
                                    current_statement_begin__ = 153;
                                    for (int pa = 1; pa <= A; ++pa) {
                                        current_statement_begin__ = 154;
                                        stan::model::assign(n, 
                                                    stan::model::cons_list(stan::model::index_uni(mt), stan::model::cons_list(stan::model::index_uni(ma), stan::model::cons_list(stan::model::index_uni(mg), stan::model::cons_list(stan::model::index_uni(cl), stan::model::cons_list(stan::model::index_uni(ca), stan::model::nil_index_list()))))), 
                                                    (stan::model::rvalue(n, stan::model::cons_list(stan::model::index_uni(mt), stan::model::cons_list(stan::model::index_uni(ma), stan::model::cons_list(stan::model::index_uni(mg), stan::model::cons_list(stan::model::index_uni(cl), stan::model::cons_list(stan::model::index_uni(ca), stan::model::nil_index_list()))))), "n") + ((get_base1(get_base1(get_base1(get_base1(get_base1(n, mt, "n", 1), ma, "n", 2), mg, "n", 3), (cl - 1), "n", 4), pa, "n", 5) * get_base1(get_base1(get_base1(s, mg, "s", 1), ((mt + cl) - 2), "s", 2), pa, "s", 3)) * get_base1(get_base1(get_base1(p, mg, "p", 1), ca, "p", 2), pa, "p", 3))), 
                                                    "assigning variable n");
                                    }
                                }
                            }
                            current_statement_begin__ = 159;
                            for (int cl = 2; cl <= L; ++cl) {
                                current_statement_begin__ = 160;
                                for (int ca = 1; ca <= A; ++ca) {
                                    current_statement_begin__ = 161;
                                    stan::model::assign(y_vec, 
                                                stan::model::cons_list(stan::model::index_uni(y_ind), stan::model::nil_index_list()), 
                                                get_base1(get_base1(get_base1(get_base1(get_base1(x, mt, "x", 1), ma, "x", 2), mg, "x", 3), cl, "x", 4), ca, "x", 5), 
                                                "assigning variable y_vec");
                                    current_statement_begin__ = 162;
                                    stan::model::assign(y_hat, 
                                                stan::model::cons_list(stan::model::index_uni(y_ind), stan::model::nil_index_list()), 
                                                (get_base1(get_base1(get_base1(get_base1(get_base1(n, mt, "n", 1), ma, "n", 2), mg, "n", 3), cl, "n", 4), ca, "n", 5) * (1 - stan::math::exp(-(get_base1(f, ca, "f", 1))))), 
                                                "assigning variable y_hat");
                                    current_statement_begin__ = 163;
                                    stan::math::assign(y_ind, (y_ind + 1));
                                }
                            }
                        }
                    }
                }
            }
            current_statement_begin__ = 172;
            lp_accum__.add(beta_log<propto__>(h, h_alpha, h_beta));
            current_statement_begin__ = 175;
            lp_accum__.add(poisson_log<propto__>(y_vec, y_hat));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("h");
        names__.push_back("p11");
        names__.push_back("p12");
        names__.push_back("p13");
        names__.push_back("f");
        names__.push_back("p");
        names__.push_back("p_matrix");
        names__.push_back("p_matrix_annual");
        names__.push_back("p_annual");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(A);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(3);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(A);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(G);
        dims__.push_back(A);
        dims__.push_back(A);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(G);
        dims__.push_back(A);
        dims__.push_back(A);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(G);
        dims__.push_back(A);
        dims__.push_back(A);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(A);
        dims__.push_back(A);
        dims__.push_back(G);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_mmm_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        std::vector<double> h;
        size_t h_d_0_max__ = A;
        h.reserve(h_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < h_d_0_max__; ++d_0__) {
            h.push_back(in__.scalar_lub_constrain(0, 1));
        }
        size_t h_k_0_max__ = A;
        for (size_t k_0__ = 0; k_0__ < h_k_0_max__; ++k_0__) {
            vars__.push_back(h[k_0__]);
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> p11 = in__.simplex_constrain(2);
        size_t p11_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < p11_j_1_max__; ++j_1__) {
            vars__.push_back(p11(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> p12 = in__.simplex_constrain(3);
        size_t p12_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < p12_j_1_max__; ++j_1__) {
            vars__.push_back(p12(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> p13 = in__.simplex_constrain(2);
        size_t p13_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < p13_j_1_max__; ++j_1__) {
            vars__.push_back(p13(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 67;
            validate_non_negative_index("f", "A", A);
            std::vector<double> f(A, double(0));
            stan::math::initialize(f, DUMMY_VAR__);
            stan::math::fill(f, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 68;
            for (int ca = 1; ca <= A; ++ca) {
                current_statement_begin__ = 69;
                stan::model::assign(f, 
                            stan::model::cons_list(stan::model::index_uni(ca), stan::model::nil_index_list()), 
                            -(stan::math::log((1 - get_base1(h, ca, "h", 1)))), 
                            "assigning variable f");
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t f_k_0_max__ = A;
                for (size_t k_0__ = 0; k_0__ < f_k_0_max__; ++k_0__) {
                    vars__.push_back(f[k_0__]);
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 179;
            validate_non_negative_index("p", "G", G);
            validate_non_negative_index("p", "A", A);
            validate_non_negative_index("p", "A", A);
            std::vector<std::vector<std::vector<double> > > p(G, std::vector<std::vector<double> >(A, std::vector<double>(A, double(0))));
            stan::math::initialize(p, DUMMY_VAR__);
            stan::math::fill(p, DUMMY_VAR__);
            current_statement_begin__ = 181;
            validate_non_negative_index("p_matrix", "A", A);
            validate_non_negative_index("p_matrix", "A", A);
            validate_non_negative_index("p_matrix", "G", G);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > p_matrix(G, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(A, A));
            stan::math::initialize(p_matrix, DUMMY_VAR__);
            stan::math::fill(p_matrix, DUMMY_VAR__);
            current_statement_begin__ = 182;
            validate_non_negative_index("p_matrix_annual", "A", A);
            validate_non_negative_index("p_matrix_annual", "A", A);
            validate_non_negative_index("p_matrix_annual", "G", G);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > p_matrix_annual(G, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(A, A));
            stan::math::initialize(p_matrix_annual, DUMMY_VAR__);
            stan::math::fill(p_matrix_annual, DUMMY_VAR__);
            current_statement_begin__ = 183;
            validate_non_negative_index("p_annual", "A", A);
            validate_non_negative_index("p_annual", "A", A);
            validate_non_negative_index("p_annual", "G", G);
            std::vector<std::vector<std::vector<double> > > p_annual(A, std::vector<std::vector<double> >(A, std::vector<double>(G, double(0))));
            stan::math::initialize(p_annual, DUMMY_VAR__);
            stan::math::fill(p_annual, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 186;
            stan::math::assign(p, rep_array(1e-12, G, A, A));
            current_statement_begin__ = 188;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()))), 
                        get_base1(p11, 1, "p11", 1), 
                        "assigning variable p");
            current_statement_begin__ = 189;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()))), 
                        get_base1(p11, 2, "p11", 1), 
                        "assigning variable p");
            current_statement_begin__ = 190;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()))), 
                        get_base1(p12, 1, "p12", 1), 
                        "assigning variable p");
            current_statement_begin__ = 191;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()))), 
                        get_base1(p12, 2, "p12", 1), 
                        "assigning variable p");
            current_statement_begin__ = 192;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(3), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()))), 
                        get_base1(p12, 3, "p12", 1), 
                        "assigning variable p");
            current_statement_begin__ = 193;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()))), 
                        get_base1(p13, 1, "p13", 1), 
                        "assigning variable p");
            current_statement_begin__ = 194;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(3), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()))), 
                        get_base1(p13, 2, "p13", 1), 
                        "assigning variable p");
            current_statement_begin__ = 196;
            for (int mg = 1; mg <= G; ++mg) {
                current_statement_begin__ = 198;
                for (int pa = 1; pa <= A; ++pa) {
                    current_statement_begin__ = 199;
                    for (int ca = 1; ca <= A; ++ca) {
                        current_statement_begin__ = 200;
                        stan::model::assign(p_matrix, 
                                    stan::model::cons_list(stan::model::index_uni(mg), stan::model::cons_list(stan::model::index_uni(pa), stan::model::cons_list(stan::model::index_uni(ca), stan::model::nil_index_list()))), 
                                    get_base1(get_base1(get_base1(p, mg, "p", 1), ca, "p", 2), pa, "p", 3), 
                                    "assigning variable p_matrix");
                    }
                }
                current_statement_begin__ = 204;
                stan::model::assign(p_matrix_annual, 
                            stan::model::cons_list(stan::model::index_uni(mg), stan::model::nil_index_list()), 
                            mat_power(get_base1(p_matrix, mg, "p_matrix", 1), 12, pstream__), 
                            "assigning variable p_matrix_annual");
                current_statement_begin__ = 206;
                for (int pa = 1; pa <= A; ++pa) {
                    current_statement_begin__ = 207;
                    for (int ca = 1; ca <= A; ++ca) {
                        current_statement_begin__ = 208;
                        stan::model::assign(p_annual, 
                                    stan::model::cons_list(stan::model::index_uni(pa), stan::model::cons_list(stan::model::index_uni(ca), stan::model::cons_list(stan::model::index_uni(mg), stan::model::nil_index_list()))), 
                                    get_base1(get_base1(p_matrix_annual, mg, "p_matrix_annual", 1), pa, ca, "p_matrix_annual", 2), 
                                    "assigning variable p_annual");
                    }
                }
            }
            // validate, write generated quantities
            current_statement_begin__ = 179;
            size_t p_k_0_max__ = G;
            size_t p_k_1_max__ = A;
            size_t p_k_2_max__ = A;
            for (size_t k_2__ = 0; k_2__ < p_k_2_max__; ++k_2__) {
                for (size_t k_1__ = 0; k_1__ < p_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < p_k_0_max__; ++k_0__) {
                        vars__.push_back(p[k_0__][k_1__][k_2__]);
                    }
                }
            }
            current_statement_begin__ = 181;
            size_t p_matrix_j_2_max__ = A;
            size_t p_matrix_j_1_max__ = A;
            size_t p_matrix_k_0_max__ = G;
            for (size_t j_2__ = 0; j_2__ < p_matrix_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < p_matrix_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < p_matrix_k_0_max__; ++k_0__) {
                        vars__.push_back(p_matrix[k_0__](j_1__, j_2__));
                    }
                }
            }
            current_statement_begin__ = 182;
            size_t p_matrix_annual_j_2_max__ = A;
            size_t p_matrix_annual_j_1_max__ = A;
            size_t p_matrix_annual_k_0_max__ = G;
            for (size_t j_2__ = 0; j_2__ < p_matrix_annual_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < p_matrix_annual_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < p_matrix_annual_k_0_max__; ++k_0__) {
                        vars__.push_back(p_matrix_annual[k_0__](j_1__, j_2__));
                    }
                }
            }
            current_statement_begin__ = 183;
            size_t p_annual_k_0_max__ = A;
            size_t p_annual_k_1_max__ = A;
            size_t p_annual_k_2_max__ = G;
            for (size_t k_2__ = 0; k_2__ < p_annual_k_2_max__; ++k_2__) {
                for (size_t k_1__ = 0; k_1__ < p_annual_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < p_annual_k_0_max__; ++k_0__) {
                        vars__.push_back(p_annual[k_0__][k_1__][k_2__]);
                    }
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_mmm";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t h_k_0_max__ = A;
        for (size_t k_0__ = 0; k_0__ < h_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "h" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t p11_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < p11_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p11" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t p12_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < p12_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p12" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t p13_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < p13_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p13" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t f_k_0_max__ = A;
            for (size_t k_0__ = 0; k_0__ < f_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "f" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t p_k_0_max__ = G;
        size_t p_k_1_max__ = A;
        size_t p_k_2_max__ = A;
        for (size_t k_2__ = 0; k_2__ < p_k_2_max__; ++k_2__) {
            for (size_t k_1__ = 0; k_1__ < p_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < p_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << k_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t p_matrix_j_2_max__ = A;
        size_t p_matrix_j_1_max__ = A;
        size_t p_matrix_k_0_max__ = G;
        for (size_t j_2__ = 0; j_2__ < p_matrix_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < p_matrix_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < p_matrix_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p_matrix" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t p_matrix_annual_j_2_max__ = A;
        size_t p_matrix_annual_j_1_max__ = A;
        size_t p_matrix_annual_k_0_max__ = G;
        for (size_t j_2__ = 0; j_2__ < p_matrix_annual_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < p_matrix_annual_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < p_matrix_annual_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p_matrix_annual" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t p_annual_k_0_max__ = A;
        size_t p_annual_k_1_max__ = A;
        size_t p_annual_k_2_max__ = G;
        for (size_t k_2__ = 0; k_2__ < p_annual_k_2_max__; ++k_2__) {
            for (size_t k_1__ = 0; k_1__ < p_annual_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < p_annual_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p_annual" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << k_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t h_k_0_max__ = A;
        for (size_t k_0__ = 0; k_0__ < h_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "h" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t p11_j_1_max__ = (2 - 1);
        for (size_t j_1__ = 0; j_1__ < p11_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p11" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t p12_j_1_max__ = (3 - 1);
        for (size_t j_1__ = 0; j_1__ < p12_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p12" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t p13_j_1_max__ = (2 - 1);
        for (size_t j_1__ = 0; j_1__ < p13_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p13" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t f_k_0_max__ = A;
            for (size_t k_0__ = 0; k_0__ < f_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "f" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t p_k_0_max__ = G;
        size_t p_k_1_max__ = A;
        size_t p_k_2_max__ = A;
        for (size_t k_2__ = 0; k_2__ < p_k_2_max__; ++k_2__) {
            for (size_t k_1__ = 0; k_1__ < p_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < p_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << k_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t p_matrix_j_2_max__ = A;
        size_t p_matrix_j_1_max__ = A;
        size_t p_matrix_k_0_max__ = G;
        for (size_t j_2__ = 0; j_2__ < p_matrix_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < p_matrix_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < p_matrix_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p_matrix" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t p_matrix_annual_j_2_max__ = A;
        size_t p_matrix_annual_j_1_max__ = A;
        size_t p_matrix_annual_k_0_max__ = G;
        for (size_t j_2__ = 0; j_2__ < p_matrix_annual_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < p_matrix_annual_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < p_matrix_annual_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p_matrix_annual" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t p_annual_k_0_max__ = A;
        size_t p_annual_k_1_max__ = A;
        size_t p_annual_k_2_max__ = G;
        for (size_t k_2__ = 0; k_2__ < p_annual_k_2_max__; ++k_2__) {
            for (size_t k_1__ = 0; k_1__ < p_annual_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < p_annual_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p_annual" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << k_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
    }
}; // model
}  // namespace
typedef model_mmm_namespace::model_mmm stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
